version: '3.4'
services:
  eureka-server:
    container_name: eureka-server
    image: eureka-server  # Debe estar en minúsculas
    build: ./EurekaServer
    ports: 
      - "8084:8084"
    networks: 
      - microservices-tecsup

  config-server:
    container_name: config-server
    image: config-server
    build: ./ConfigServer
    ports:
      - 8889:8889
    healthcheck:
      test: "curl http://config-server:8889/productos-api/dev"
      interval: 10s
      timeout: 2s
      retries: 3
    networks:
      - microservices-tecsup

  api-gateway:  # Cambiado a minúsculas
    container_name: api-gateway-server  # Cambiado a minúsculas
    image: api-gateway  # Cambiado a minúsculas
    build: ./ApiGateway
    ports: 
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8084/eureka/
    networks: 
      - microservices-tecsup

  dbmysql:
    container_name: dbmysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: tiendaapi
      MYSQL_ROOT_PASSWORD: mysqladmin
    volumes: 
      - db-data:/var/lib/mysql
      - ./database/tiendaapi.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports: 
      - "3306:3306"
    networks: 
      - microservices-tecsup

  productos-api:
    container_name: productos-api
    image: productos-api
    build: ./ProductosAPI
    restart: always
    ports:
      - 8082:8082
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:8084/eureka/
      - CONFIG_SERVER_URI=http://config-server:8889
    depends_on:
      eureka-server:
        condition: service_started
      api-gateway:
        condition: service_started
      config-server:
        condition: service_healthy
      dbmysql:
        condition: service_started
    networks:
      - microservices-tecsup
    
volumes:
  db-data:
networks:
  microservices-tecsup:
